// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SilentMoon.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SilentMoon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818073226_TranslationAdded")]
    partial class TranslationAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SilentMoon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FirstName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("RefreshTokenId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Slug")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TranslationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Type")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TranslationId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DurationSec")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("NarratorType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Subtitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TranslationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Type")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TranslationId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Token")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("IconKey")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Slug")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TranslationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("TranslationId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 8, 18, 11, 32, 26, 15, DateTimeKind.Local).AddTicks(9307),
                            IconKey = "betterSleep.png",
                            IsDeleted = false,
                            Slug = "Sleep",
                            Title = "Better Sleep"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 8, 18, 11, 32, 26, 15, DateTimeKind.Local).AddTicks(9319),
                            IconKey = "reduceStress.png",
                            IsDeleted = false,
                            Slug = "Stress",
                            Title = "Reduce Stressed"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 8, 18, 11, 32, 26, 15, DateTimeKind.Local).AddTicks(9321),
                            IconKey = "reduceAnxiety.png",
                            IsDeleted = false,
                            Slug = "Anxiety",
                            Title = "Reduce Anxiety"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 8, 18, 11, 32, 26, 15, DateTimeKind.Local).AddTicks(9322),
                            IconKey = "increaseHappiness.png",
                            IsDeleted = false,
                            Slug = "Happiness",
                            Title = "Increase Happiness"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 8, 18, 11, 32, 26, 15, DateTimeKind.Local).AddTicks(9323),
                            IconKey = "improvePerformance.png",
                            IsDeleted = false,
                            Slug = "Performance",
                            Title = "Improve Performance"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 8, 18, 11, 32, 26, 15, DateTimeKind.Local).AddTicks(9324),
                            IconKey = "personalGrowth.png",
                            IsDeleted = false,
                            Slug = "Growth",
                            Title = "Personal Growth"
                        });
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.Translation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("RelationalId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Translation_AZ")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Translation_EN")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Translation_RU")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.UserTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TopicId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTopics");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.Category", b =>
                {
                    b.HasOne("SilentMoon.Domain.Entities.Translation", "Translation")
                        .WithMany()
                        .HasForeignKey("TranslationId");

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.Course", b =>
                {
                    b.HasOne("SilentMoon.Domain.Entities.Translation", "Translation")
                        .WithMany()
                        .HasForeignKey("TranslationId");

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SilentMoon.Domain.Entities.ApplicationUser", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("SilentMoon.Domain.Entities.RefreshToken", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.Topic", b =>
                {
                    b.HasOne("SilentMoon.Domain.Entities.Translation", "Translation")
                        .WithMany()
                        .HasForeignKey("TranslationId");

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.UserTopic", b =>
                {
                    b.HasOne("SilentMoon.Domain.Entities.Topic", "Topic")
                        .WithMany("UserTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilentMoon.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserTopics")
                        .HasForeignKey("UserId");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("RefreshToken");

                    b.Navigation("UserTopics");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.Topic", b =>
                {
                    b.Navigation("UserTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
