// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SilentMoon.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SilentMoon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SilentMoon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FirstName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("RefreshTokenId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Token")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SilentMoon.Domain.Entities.ApplicationUser", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("SilentMoon.Domain.Entities.RefreshToken", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
