<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Pomodoros\**" />
    <EmbeddedResource Remove="Features\Pomodoros\**" />
    <None Remove="Features\Pomodoros\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SilentMoon.SharedKernel\SilentMoon.SharedKernel.csproj" />
    <ProjectReference Include="..\SilentMoon.Domain\SilentMoon.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\ViewModels\" />
    <Folder Include="Mappings\" />
  </ItemGroup>

</Project>
